language: node_js

node_js:
  - "0.10"

env:
 global:
  - secure: "YKYRdmBROtuZFXgh+SQPPx7hvexZmNlo6Pe9cbBBjWbKCO0a8RAtyMdrNRC5AC4ySW0NJWqYnj6yjLorRhzQ1YeJxJOQ9AvObXVG4JxTUh6WNLKUCw2g7oEBBSyRFJAkkFt7FUw2GWBYPjiyePSW04ZSUE1mLD+x4EbO3TAVfPw="

branches:
 only:
  - master

install:
  - ./script/bootstrap.sh

script:
  - ./script/travis.sh
