language: node_js

node_js:
  - "0.10"

branches:
 only:
  - master

before_install:
  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc

install:
  - ./script/bootstrap.sh

script:
  - ./script/travis.sh
